In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.drop('species', axis=1)
y = df['species']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# KNN

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
model_knn5 = KNeighborsClassifier(n_neighbors=5)

In [47]:
model_knn5.fit(X_train, y_train)

KNeighborsClassifier()

In [49]:
model_knn5.score(X_test, y_test)

0.98

In [94]:
# Changing the value of n_neighbors=9
model_knn9 = KNeighborsClassifier(n_neighbors=9)

In [96]:
model_knn9.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [98]:
model_knn9.score(X_test, y_test)

0.98

In [100]:
# Changing the value of n_neighbors=13
model_knn13 = KNeighborsClassifier(n_neighbors=13)

In [102]:
model_knn13.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [104]:
model_knn13.score(X_test, y_test)

1.0

# SVM

In [62]:
from sklearn.svm import SVC

In [121]:
model_svm_nopara = SVC(gamma='auto')

In [123]:
model_svm_nopara.fit(X_train, y_train)

SVC(gamma='auto')

In [125]:
model_svm_nopara.score(X_test, y_test)

1.0

In [127]:
# Using parameters
model_svm = SVC(C=30, kernel='rbf', gamma='auto')

In [129]:
model_svm.fit(X_train, y_train)

SVC(C=30, gamma='auto')

In [131]:
model_svm.score(X_test, y_test)

0.98

In [133]:
# Changing the value of kernel='linear'
model_svm_kernel = SVC(C=30, kernel='linear', gamma='auto')

In [135]:
model_svm_kernel.fit(X_train, y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [137]:
model_svm_kernel.score(X_test, y_test)

0.98

In [139]:
# Changing the value of C=10
model_svm_C = SVC(C=10, kernel='linear', gamma='auto')

In [141]:
model_svm_C.fit(X_train, y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [143]:
model_svm_C.score(X_test, y_test)

1.0

# Grid Search CV

In [146]:
from sklearn.model_selection import GridSearchCV

In [148]:
classifier = GridSearchCV((model_svm_nopara), {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear'],
}, cv=5, return_train_score=False)

In [150]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [152]:
classifier.cv_results_

{'mean_fit_time': array([0.01111064, 0.00728078, 0.00775356, 0.00732694, 0.00709429,
        0.00653377, 0.00817823, 0.00708728]),
 'std_fit_time': array([0.00649929, 0.00113014, 0.00130446, 0.00129672, 0.00062079,
        0.00022906, 0.00112727, 0.00065616]),
 'mean_score_time': array([0.00583191, 0.0048975 , 0.00557756, 0.00486741, 0.00559793,
        0.00494771, 0.00539694, 0.0061245 ]),
 'std_score_time': array([0.00120836, 0.00050874, 0.00049352, 0.00056475, 0.00054424,
        0.00057629, 0.00064153, 0.00099483]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [154]:
results = pd.DataFrame(classifier.cv_results_)

In [158]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011111,0.006499,0.005832,0.001208,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.007281,0.001130,0.004897,0.000509,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.007754,0.001304,0.005578,0.000494,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.007327,0.001297,0.004867,0.000565,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.007094,0.000621,0.005598,0.000544,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.006534,0.000229,0.004948,0.000576,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.008178,0.001127,0.005397,0.000642,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.007087,0.000656,0.006124,0.000995,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [160]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

# Randam Search CV

In [163]:
from sklearn.model_selection import RandomizedSearchCV

In [165]:
classifier_r = RandomizedSearchCV((model_svm_nopara), {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear'],
}, n_iter=4, cv=5, return_train_score=False)

In [167]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [173]:
results_r = pd.DataFrame(classifier_r.cv_results_)

In [175]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1        1          rbf         0.980000
2       30       linear         0.960000
3       20       linear         0.966667